import { Inter } from "next/font/google";
import { Providers } from "./contexts/Providers";

export const mainFont = Inter({ subsets: ["latin"], variable: "--main-font" });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="pt-br">
			<body className={`${mainFont.className}`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
